[versions]
architectury = "3.4-SNAPSHOT"
fabric_loom = "1.13-SNAPSHOT"
fabric_loader = "0.18.3"
neoforge = "21.7.25-beta"

minecraft1_21_11 = "1.21.11"
fabric_api1_21_11 = "0.140.0+1.21.11"
modmenu1_21_11 = "15.0.0"
yacl1_21_11 = "3.8.1+1.21.11-fabric"

minecraft1_21_10 = "1.21.10"
fabric_api1_21_10 = "0.138.4+1.21.10"
modmenu1_21_10 = "15.0.0"
yacl1_21_10 = "3.8.1+1.21.10-fabric"

minecraft1217 = "1.21.7"
fabric_api1217 = "0.129.0+1.21.7"
modmenu1217 = "15.0.0"
yacl1217 = "3.7.1+1.21.6-fabric"
yacl1217f = "3.7.1+1.21.6-neoforge"

minecraft1215 = "1.21.5"
fabric_api1215 = "0.128.1+1.21.5"
modmenu1215 = "13.0.3"
yacl1215 = "3.7.1+1.21.5-fabric"

minecraft1214 = "1.21.4"
fabric_api1214 = "0.119.3+1.21.4"
modmenu1214 = "13.0.3"
yacl1214 = "3.6.2+1.21.4-fabric"

minecraft1213 = "1.21.3"
fabric_api1213 = "0.114.1+1.21.3"
modmenu1213 = "11.0.1"
yacl1213 = "3.6.1+1.21.2-fabric"

minecraft1210 = "1.21"
fabric_api1210 = "0.102.0+1.21"
modmenu1210 = "11.0.1"
yacl1210 = "3.5.0+1.21-fabric"

minecraft1206 = "1.20.6"
fabric_api1206 = "0.100.8+1.20.6"
modmenu1206 = "10.0.0"
yacl1206 = "3.5.0+1.20.6-fabric"

minecraft1201 = "1.20.1"
fabric_api1201 = "0.92.5+1.20.1"
modmenu1201 = "7.2.2"
yacl1201 = "3.5.0+1.20.1-fabric"

paper_api = "1.20.1-R0.1-SNAPSHOT"
netty_buffer = "4.1.112.Final"

[libraries]
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }
neoforge = { module = "net.neoforged:neoforge", version.ref = "neoforge" }

minecraft1_21_11 = { module = "com.mojang:minecraft", version.ref = "minecraft1_21_11" }
fabric_api1_21_11 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api1_21_11" }
modmenu1_21_11 = { module = "com.terraformersmc:modmenu", version.ref = "modmenu1_21_11" }
yacl1_21_11 = { module = "dev.isxander:yet-another-config-lib", version.ref = "yacl1_21_11" }

minecraft1_21_10 = { module = "com.mojang:minecraft", version.ref = "minecraft1_21_10" }
fabric_api1_21_10 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api1_21_10" }
modmenu1_21_10 = { module = "com.terraformersmc:modmenu", version.ref = "modmenu1_21_10" }
yacl1_21_10 = { module = "dev.isxander:yet-another-config-lib", version.ref = "yacl1_21_10" }

minecraft1217 = { module = "com.mojang:minecraft", version.ref = "minecraft1217" }
fabric_api1217 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api1217" }
modmenu1217 = { module = "com.terraformersmc:modmenu", version.ref = "modmenu1217" }
yacl1217 = { module = "dev.isxander:yet-another-config-lib", version.ref = "yacl1217" }
yacl1217f = { module = "dev.isxander:yet-another-config-lib", version.ref = "yacl1217f" }

minecraft1215 = { module = "com.mojang:minecraft", version.ref = "minecraft1215" }
fabric_api1215 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api1215" }
modmenu1215 = { module = "com.terraformersmc:modmenu", version.ref = "modmenu1215" }
yacl1215 = { module = "dev.isxander:yet-another-config-lib", version.ref = "yacl1215" }

minecraft1214 = { module = "com.mojang:minecraft", version.ref = "minecraft1214" }
fabric_api1214 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api1214" }
modmenu1214 = { module = "com.terraformersmc:modmenu", version.ref = "modmenu1214" }
yacl1214 = { module = "dev.isxander:yet-another-config-lib", version.ref = "yacl1214" }

minecraft1213 = { module = "com.mojang:minecraft", version.ref = "minecraft1213" }
fabric_api1213 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api1213" }
modmenu1213 = { module = "com.terraformersmc:modmenu", version.ref = "modmenu1213" }
yacl1213 = { module = "dev.isxander:yet-another-config-lib", version.ref = "yacl1213" }

minecraft1210 = { module = "com.mojang:minecraft", version.ref = "minecraft1210" }
fabric_api1210 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api1210" }
modmenu1210 = { module = "com.terraformersmc:modmenu", version.ref = "modmenu1210" }
yacl1210 = { module = "dev.isxander:yet-another-config-lib", version.ref = "yacl1210" }

minecraft1206 = { module = "com.mojang:minecraft", version.ref = "minecraft1206" }
fabric_api1206 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api1206" }
modmenu1206 = { module = "com.terraformersmc:modmenu", version.ref = "modmenu1206" }
yacl1206 = { module = "dev.isxander:yet-another-config-lib", version.ref = "yacl1206" }

minecraft1201 = { module = "com.mojang:minecraft", version.ref = "minecraft1201" }
fabric_api1201 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api1201" }
modmenu1201 = { module = "com.terraformersmc:modmenu", version.ref = "modmenu1201" }
yacl1201 = { module = "dev.isxander:yet-another-config-lib", version.ref = "yacl1201" }

paper_api = { module = "io.papermc.paper:paper-api", version.ref = "paper_api" }
netty_buffer = { module = "io.netty:netty-buffer", version.ref = "netty_buffer" }

[plugins]
fabric_loom = { id = "dev.architectury.loom", version.ref = "fabric_loom" }
architectury = { id = "architectury-plugin", version.ref = "architectury" }
