[versions]
fabric_loader = "0.16.8"

minecraft1213 = "1.21.3"
fabric_mappings1213 = "1.21.3+build.2"
fabric_api1213 = "0.107.0+1.21.3"
modmenu1213 = "11.0.1"
yacl1213 = "3.6.1+1.21.2-fabric"

minecraft121 = "1.21"
fabric_mappings121 = "1.21+build.9"
fabric_api121 = "0.102.0+1.21"
modmenu121 = "11.0.1"
yacl121 = "3.5.0+1.21-fabric"

minecraft1206 = "1.20.6"
fabric_mappings1206 = "1.20.6+build.3"
fabric_api1206 = "0.100.8+1.20.6"
modmenu1206 = "10.0.0"
yacl1206 = "3.5.0+1.20.6-fabric"

minecraft1201 = "1.20.1"
fabric_mappings1201 = "1.20.1+build.10"
fabric_api1201 = "0.92.2+1.20.1"
modmenu1201 = "7.2.2"
yacl1201 = "3.5.0+1.20.1-fabric"

minecraft1194 = "1.19.4"
fabric_mappings1194 = "1.19.4+build.2"
fabric_api1194 = "0.87.2+1.19.4"
modmenu1194 = "6.3.1"
yacl1194 = "3.1.1+1.19.4"

paper_api = "1.20.1-R0.1-SNAPSHOT"
netty_buffer = "4.1.112.Final"

[libraries]
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }

minecraft1213 = { module = "com.mojang:minecraft", version.ref = "minecraft1213" }
fabric_mappings1213 = { module = "net.fabricmc:yarn", version.ref = "fabric_mappings1213" }
fabric_api1213 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api1213" }
modmenu1213 = { module = "com.terraformersmc:modmenu", version.ref = "modmenu1213" }
yacl1213 = { module = "dev.isxander:yet-another-config-lib", version.ref = "yacl1213" }

minecraft121 = { module = "com.mojang:minecraft", version.ref = "minecraft121" }
fabric_mappings121 = { module = "net.fabricmc:yarn", version.ref = "fabric_mappings121" }
fabric_api121 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api121" }
modmenu121 = { module = "com.terraformersmc:modmenu", version.ref = "modmenu121" }
yacl121 = { module = "dev.isxander:yet-another-config-lib", version.ref = "yacl121" }

minecraft1206 = { module = "com.mojang:minecraft", version.ref = "minecraft1206" }
fabric_mappings1206 = { module = "net.fabricmc:yarn", version.ref = "fabric_mappings1206" }
fabric_api1206 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api1206" }
modmenu1206 = { module = "com.terraformersmc:modmenu", version.ref = "modmenu1206" }
yacl1206 = { module = "dev.isxander:yet-another-config-lib", version.ref = "yacl1206" }

minecraft1201 = { module = "com.mojang:minecraft", version.ref = "minecraft1201" }
fabric_mappings1201 = { module = "net.fabricmc:yarn", version.ref = "fabric_mappings1201" }
fabric_api1201 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api1201" }
modmenu1201 = { module = "com.terraformersmc:modmenu", version.ref = "modmenu1201" }
yacl1201 = { module = "dev.isxander:yet-another-config-lib", version.ref = "yacl1201" }

minecraft1194 = { module = "com.mojang:minecraft", version.ref = "minecraft1194" }
fabric_mappings1194 = { module = "net.fabricmc:yarn", version.ref = "fabric_mappings1194" }
fabric_api1194 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api1194" }
modmenu1194 = { module = "com.terraformersmc:modmenu", version.ref = "modmenu1194" }
yacl1194 = { module = "dev.isxander.yacl:yet-another-config-lib-fabric", version.ref = "yacl1194" }

paper_api = { module = "io.papermc.paper:paper-api", version.ref = "paper_api" }
netty_buffer = { module = "io.netty:netty-buffer", version.ref = "netty_buffer" }

[plugins]
fabric_loom = { id = "fabric-loom", version = "1.8.9" }
