[versions]
architectury = "3.4-SNAPSHOT"
fabric_loom = "1.13-SNAPSHOT"
fabric_loader = "0.18.3"
neoforge = "21.7.25-beta"

minecraft1_21_11 = "1.21.11"
fabric_api1_21_11 = "0.140.0+1.21.11"
modmenu1_21_11 = "15.0.0"
yacl1_21_11 = "3.8.1+1.21.11-fabric"

minecraft1_21_10 = "1.21.10"
fabric_api1_21_10 = "0.138.4+1.21.10"
modmenu1_21_10 = "15.0.0"
yacl1_21_10 = "3.8.1+1.21.10-fabric"

minecraft1_21_7 = "1.21.7"
fabric_api1_21_7 = "0.129.0+1.21.7"
modmenu1_21_7 = "15.0.0"
yacl1_21_7 = "3.7.1+1.21.6-fabric"
yacl1_21_7f = "3.7.1+1.21.6-neoforge"

minecraft1_21_5 = "1.21.5"
fabric_api1_21_5 = "0.128.1+1.21.5"
modmenu1_21_5 = "13.0.3"
yacl1_21_5 = "3.7.1+1.21.5-fabric"

minecraft1_21_4 = "1.21.4"
fabric_api1_21_4 = "0.119.3+1.21.4"
modmenu1_21_4 = "13.0.3"
yacl1_21_4 = "3.6.2+1.21.4-fabric"

minecraft1_21_3 = "1.21.3"
fabric_api1_21_3 = "0.114.1+1.21.3"
modmenu1_21_3 = "11.0.1"
yacl1_21_3 = "3.6.1+1.21.2-fabric"

minecraft1_21_0 = "1.21"
fabric_api1_21_0 = "0.102.0+1.21"
modmenu1_21_0 = "11.0.1"
yacl1_21_0 = "3.5.0+1.21-fabric"

minecraft1_20_6 = "1.20.6"
fabric_api1_20_6 = "0.100.8+1.20.6"
modmenu1_20_6 = "10.0.0"
yacl1_20_6 = "3.5.0+1.20.6-fabric"

minecraft1_20_1 = "1.20.1"
fabric_api1_20_1 = "0.92.5+1.20.1"
modmenu1_20_1 = "7.2.2"
yacl1_20_1 = "3.5.0+1.20.1-fabric"

paper_api = "1.20.1-R0.1-SNAPSHOT"
netty_buffer = "4.1.112.Final"

[libraries]
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }
neoforge = { module = "net.neoforged:neoforge", version.ref = "neoforge" }

minecraft1_21_11 = { module = "com.mojang:minecraft", version.ref = "minecraft1_21_11" }
fabric_api1_21_11 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api1_21_11" }
modmenu1_21_11 = { module = "com.terraformersmc:modmenu", version.ref = "modmenu1_21_11" }
yacl1_21_11 = { module = "dev.isxander:yet-another-config-lib", version.ref = "yacl1_21_11" }

minecraft1_21_10 = { module = "com.mojang:minecraft", version.ref = "minecraft1_21_10" }
fabric_api1_21_10 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api1_21_10" }
modmenu1_21_10 = { module = "com.terraformersmc:modmenu", version.ref = "modmenu1_21_10" }
yacl1_21_10 = { module = "dev.isxander:yet-another-config-lib", version.ref = "yacl1_21_10" }

minecraft1_21_7 = { module = "com.mojang:minecraft", version.ref = "minecraft1_21_7" }
fabric_api1_21_7 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api1_21_7" }
modmenu1_21_7 = { module = "com.terraformersmc:modmenu", version.ref = "modmenu1_21_7" }
yacl1_21_7 = { module = "dev.isxander:yet-another-config-lib", version.ref = "yacl1_21_7" }
yacl1_21_7f = { module = "dev.isxander:yet-another-config-lib", version.ref = "yacl1_21_7f" }

minecraft1_21_5 = { module = "com.mojang:minecraft", version.ref = "minecraft1_21_5" }
fabric_api1_21_5 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api1_21_5" }
modmenu1_21_5 = { module = "com.terraformersmc:modmenu", version.ref = "modmenu1_21_5" }
yacl1_21_5 = { module = "dev.isxander:yet-another-config-lib", version.ref = "yacl1_21_5" }

minecraft1_21_4 = { module = "com.mojang:minecraft", version.ref = "minecraft1_21_4" }
fabric_api1_21_4 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api1_21_4" }
modmenu1_21_4 = { module = "com.terraformersmc:modmenu", version.ref = "modmenu1_21_4" }
yacl1_21_4 = { module = "dev.isxander:yet-another-config-lib", version.ref = "yacl1_21_4" }

minecraft1_21_3 = { module = "com.mojang:minecraft", version.ref = "minecraft1_21_3" }
fabric_api1_21_3 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api1_21_3" }
modmenu1_21_3 = { module = "com.terraformersmc:modmenu", version.ref = "modmenu1_21_3" }
yacl1_21_3 = { module = "dev.isxander:yet-another-config-lib", version.ref = "yacl1_21_3" }

minecraft1_21_0 = { module = "com.mojang:minecraft", version.ref = "minecraft1_21_0" }
fabric_api1_21_0 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api1_21_0" }
modmenu1_21_0 = { module = "com.terraformersmc:modmenu", version.ref = "modmenu1_21_0" }
yacl1_21_0 = { module = "dev.isxander:yet-another-config-lib", version.ref = "yacl1_21_0" }

minecraft1_20_6 = { module = "com.mojang:minecraft", version.ref = "minecraft1_20_6" }
fabric_api1_20_6 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api1_20_6" }
modmenu1_20_6 = { module = "com.terraformersmc:modmenu", version.ref = "modmenu1_20_6" }
yacl1_20_6 = { module = "dev.isxander:yet-another-config-lib", version.ref = "yacl1_20_6" }

minecraft1_20_1 = { module = "com.mojang:minecraft", version.ref = "minecraft1_20_1" }
fabric_api1_20_1 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api1_20_1" }
modmenu1_20_1 = { module = "com.terraformersmc:modmenu", version.ref = "modmenu1_20_1" }
yacl1_20_1 = { module = "dev.isxander:yet-another-config-lib", version.ref = "yacl1_20_1" }

paper_api = { module = "io.papermc.paper:paper-api", version.ref = "paper_api" }
netty_buffer = { module = "io.netty:netty-buffer", version.ref = "netty_buffer" }

[plugins]
fabric_loom = { id = "dev.architectury.loom", version.ref = "fabric_loom" }
architectury = { id = "architectury-plugin", version.ref = "architectury" }
